language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "6"
sudo: false
before_script:
  - npm install -g mocha
  - npm install -g gulp
script: gulp
after_script:
  - npm run coveralls
after_success: